### ISSUE TITLE
Manage properly the way to extend an existing namespace

### ISSUE THREAD

**Issue by ThomasG77** [webgeodatavore/ol3-photon#3]
When the library is in standalone context with html (using a separate `<script>` call), it works.

When I try to use `require`, I have an error because I've done a dirty hack at  to extend namespace.
There should be a better way

**Comment by walkermatt** [comment]
Have you looked at how similar libs such as "leaflet-control-geocoder":https://github.com/perliedman/leaflet-control-geocoder/blob/master/Control.Geocoder.js handle it?

I'm wondering in future about doing without module magic in a lib and instead assuming users will be using a build tool such as Browserify to combine libs which will handle the magic for them as proposed in "this post":http://dontkry.com/posts/code/browserify-and-the-universal-module-definition.html.

**Comment by ThomasG77** [comment]
I solved my problem using namespace export in Browserify.

@walkermatt In fact, as I wasn't aware of the standalone syntax with dot-syntax when building with Browserify ([see it](https://github.com/webgeodatavore/ol3-photon/commit/204de33d7159511aece2657d8b752c43d7ce7b2d#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L10)), I was overloading(and hacking) the `ol` lib, with a jQuery plugin pattern ([see diff](https://github.com/webgeodatavore/ol3-photon/commit/204de33d7159511aece2657d8b752c43d7ce7b2d#diff-9b6186c550b145e11b16272a839001b0L496)) to bypass the issue.
In fact, Browserify already use the "Universal Access" syntax (deminify [ol3.photon.min.js](https://github.com/webgeodatavore/ol3-photon/blob/master/dist/ol3.photon.min.js) with jsbeautifier to confirm)

Concerning the future, IMO, Browserify or Webpack should always be used but it takes times and some people prefer simply concatenate files with builder like Gulp like here https://blog.nodejitsu.com/npmawesome-9-gulp-plugins/#gulpconcat
You should also consider the [JSPM](http://jspm.io) rising coupled with [SystemJS](https://github.com/systemjs/systemjs) loader to manage dependencies due to ES6 module support, ES6 feature backported with Babel or Traceur
For JSPM and SystemJS, this [blog post](http://javascriptplayground.com/blog/2014/11/js-modules-jspm-systemjs/) was interesting to grasp the change.
